import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ConnectKitButton } from "connectkit";
import { useAccount } from "wagmi";
import { prepareWriteContract, writeContract } from '@wagmi/core'
const fs = require("fs")
const path = require("path")

export default function Home() {
  const { address, isConnected, isDisconnected } = useAccount();
  const dir = path.resolve(
    __dirname,
    "../artifacts/contracts/PaperScoreNFT.sol/PaperScore.json"
  );
  const file = fs.readFileSync(dir, "utf8")
  const json = JSON.parse(file)
  const contractAbi = json.abi;
  const config = await prepareWriteContract({
    address: '0xecb504d39723b0be0e3a9aa33d646642d1051ee1',
    abi: wagmigotchiABI,
    functionName: 'mint',
    args: [],
  })
  // const mint = await writeContract(config);
  return (
    <div className={styles.container}>
      <Head>
        <title>Paper Score NFT minter</title>
        <meta name='description' content='Generated by Paper Score' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <ConnectKitButton />
        {isConnected ? "" : ""}
        {/* <ConnectKitButton.Custom>
          {({
            isConnected,
            isConnecting,
            show,
            hide,
            truncatedAddress,
            ensName,
          }) => {
            return (
              <StyledButton onClick={show}>
                {isConnected ? ensName ?? truncatedAddress : "Mint"}
              </StyledButton>
            );
          }}
        </ConnectKitButton.Custom> */}
      </main>
    </div>
  );
}
