import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {ConnectKitButton} from "connectkit";

export default function Home() {
  return (
   
    <div className={styles.container}>
      <Head>
        <title>Paper Score NFT minter</title>
        <meta name="description" content="Generated by Paper Score" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <ConnectKitButton />
      {/* <ConnectKitButton.Custom>
      {({ isConnected, isConnecting, show, hide, address, ensName }) => {
        return (
          <button onClick={show} >
            {isConnected ? address : "Custom Connect"}
          </button>
        );
      }}
    </ConnectKitButton.Custom> */}
      </main>
    </div>
  )
}
